## 회귀분석 (Regression)


- 독립변수(X)와 종속변수(Y)의 관계식에서
  독립변수가 한 단위 증가할 때 종속변수가 얼마나 영향을 받는지 분석
  

[예] 연속형변수와 연속형 변수를 비교할 때


- 나이(X)가 많을 수록 소득(Y)가 높은지 분석
- 광고지불비(X)에 따라 판매량이 영향을 받는지 분석
- 가계 수입과 사교육비 지출 사이에 관계가 있는지 분석



[참고그림] '모두의 딥러닝' 교재에서

<img src='./imgs/regression1.png' width='500'>
<img src='./imgs/regression2.png' width='500'>
<img src='./imgs/regression3.png' width='500'>

** 회귀분석 종류

1) 단순회귀 분석 : 독립변수가 1개
        
        ` 광고지불비(X)를 이용하여 상품 매출액(Y) 예측할 때
        
2) 다중회귀 분석 : 독립변수가 2개 이상
       
       ` 어린이 연령(X1)과 하루 평균 학습시간(X2)를 이용하여 그 어린이의 성적(Y)을 예측하고자 할 때



---
#### 앞에서는   scipy 의 선형회귀를 이용하고 아래는 sklearn의 머신러닝 종류 중 선형회귀 모델 사용

---

## 회귀분석 예제 - 보스턴 주택가격



#### [ 절차 ]
    (1) 데이타 읽어오기

    (2) 데이터와 레이블 분리 변수 선언

    (3) 훈련데이터와 테스트 데이터로 분리하기

    (4) 모델로 학습하기

    (5) 검증하기

In [2]:
#!pip install sklearn

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.
  
  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
  
  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]
  
  note: This error originates from a subpr

In [4]:

# 보스턴 주택가격 데이터셋
from sklearn.datasets import fetch_california_housing

# 회귀분석을 위한 패키기
from sklearn.linear_model import LinearRegression

# 학습용, 검증용 데이터를 나누기 위한 패키기
from sklearn.model_selection import train_test_split

In [5]:
boston = fetch_california_housing()
boston

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [6]:
print(boston.data.shape) #기본적으로 딕셔너리 구조로 만들어준다.

(20640, 8)


In [8]:
print(boston.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

    Attribute Information:
        - MedInc      : 수입의 중앙값  
        - HouseAge    : 집년도의 중앙값  
        - AveRooms    : 가구당 평균 방의 수  
        - AveBedrms   : 가구당 평균 침실 수  
        - Population  : 해당 블럭의 인구수  
        - AveOccup    : 평균 가족 구성원 수  
        - Latitude    : 해당 블럭의 위도  
        - Longitude   : 해당 블럭의 경도  

In [10]:
type(boston.data)

numpy.ndarray

numpy.ndarray의 타입이 나오는데 컨드롤 하기가  
너무 어려움이 있기 때문에  
판다스를 이용해서 데이터 사용

In [11]:
import pandas as pd

In [13]:
df = pd.DataFrame(boston.data)
df

df.columns = boston.feature_names
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

### 데이터와 레이블 분리 변수 선언

In [15]:
x = df
x

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [16]:
y = boston.target
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

### 데이터 셋에서 훈련데이터와 테스트(검증)데이터로 나누기  
보통 일반적으로 (7:3)으로 나누기도 하고 (8:2)로 나누기도 한다.

In [49]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0) 
# 훈련데이터를 7 검증 데이터를 3으로 나눈값 random_state은 0으로 초기 설정
#x_train :훈련데이터
#x_test : 테스트데이터
#y_train :훈련데이터의 답
#y_test: 테스트데이터의 답

In [50]:
x_train.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
12069  4.2386       6.0  7.723077   1.169231       228.0  3.507692     33.83   
15925  4.3898      52.0  5.326622   1.100671      1485.0  3.322148     37.73   
11162  3.9333      26.0  4.668478   1.046196      1022.0  2.777174     33.83   
4904   1.4653      38.0  3.383495   1.009709       749.0  3.635922     34.01   
4683   3.1765      52.0  4.119792   1.043403      1135.0  1.970486     34.08   

       Longitude  
12069    -117.55  
15925    -122.44  
11162    -118.00  
4904     -118.26  
4683     -118.36

In [51]:
y_train[:5] #훈련 데이터의 답은 numpy값으로 나온다.

array([5.00001, 2.7    , 1.961  , 1.188  , 2.25   ])

### 훈련데이터 학습하기

In [52]:
lr = LinearRegression()

lr.fit(x_train,y_train)

LinearRegression()

### 검증하기

In [53]:
print("훈련데이터셋 점수: {:.2f}".format(lr.score(x_train,y_train)))
print("테스트데이터셋 점수: {:.2f}".format(lr.score(x_test,y_test)))

훈련데이터셋 점수: 0.61
테스트데이터셋 점수: 0.59


### 예측하기

In [54]:
x.head(1)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127    1.02381       322.0  2.555556     37.88   

   Longitude  
0    -122.23

In [55]:
y[1]

3.585

In [57]:
import numpy as np

In [63]:
sample_x = np.array([[8.3252,41.0,6.984127,1.02381,322.0,2.555556,37.88,-122.23]])
sample_x

array([[   8.3252  ,   41.      ,    6.984127,    1.02381 ,  322.      ,
           2.555556,   37.88    , -122.23    ]])

In [65]:
sample_y = lr.predict(sample_x)
sample_y

C:\Users\ict03_013\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.13749617])

In [66]:
#정확도 60퍼센트의 확률로 4.1.의 값을 가질거 같다고 예상