 # * sklearn 라이브러리에서 간단한 분류 모델

 ## - KNN 

 
* KNN (K-Nearest Neighbors) : 최근접 분류기
	새로운 데이터가 들어오면 훈련데이타 중에서 가장 가까운 데이터 K개를 찾는다.
	이 중에서 빈도가 높은 label(결과)을 새 데이터의 레이블로 예측한다. 


<img src='./imgs/knn.png' width='500' height='380'>


### * 절차

(1) 데이타 읽어오기

(2) 데이터와 레이블 분리 변수 선언

(3) 훈련데이터와 테스트 데이터로 분리하기

(4) 모델로 학습하기

(5) 예측하기

(6) 검증하기

(7) 정확도 측정하기

In [3]:
# (1) 데이타 읽어오기

import numpy as np
from sklearn import datasets

iris = datasets.load_iris()



In [8]:
# (2) 데이터와 레이블 분리 변수 선언 ( 이미 데이터와 레이블이 정해짐 )
X = iris['data']
#대문자 X를 보통 데이터로 정의한다.
print(X[:10])

y=iris['target']
print(y[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]


In [11]:
# (3) 훈련데이터와 테스트 데이터로 분리하기
from sklearn.model_selection import train_test_split

#기본값 훈련데이터 /테스트 데이터 = 75:25

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0)



print(X_train[:10])
print(X_test[:10])
print(y_train[:10])
print(y_test[:10])

[[5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]]
[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]]
[1 1 2 0 2 0 0 1 2 2]
[2 1 0 2 0 2 0 1 1 1]


In [14]:
# (4) 모델에 데이터를 학습하기
# 훈련데이타와 훈련레이블를 인자로 넣어 학습한 결과 knn 객체를 리턴한다
# n_neighbors : 이웃갯수 지정

from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train,y_train) #머신런닝은 그 값에 대한 레이블을 꼭 줘야한다.

KNeighborsClassifier(n_neighbors=3)

In [20]:
# (5) 새로운 샘플 데이타가 들어왔을 때 label 예측하기
# 너무 동떨어진 데이타 입력하면 결과 예측 성능이 낮기에 기존 샘플과 유사하게 만듬
newData = np.array([[5.1, 2.9, 1., 0.3]]) 

y_predict=knn.predict(newData)
print(y_predict)
print(iris['target_names'][y_predict])


[0]
['setosa']


In [23]:
# (6) 검증하기
# 실제 레이블과 예측값의 정확도 확인

print("훈련데이터 검증: {:.2f}".format(knn.score(X_train,y_train)))
print("테스트데이터 검증: {:.2f}".format(knn.score(X_test,y_test)))


훈련데이터 검증: 0.96
테스트데이터 검증: 0.97


In [25]:
# (7) 정확도 측정 
#수작업으로도 확인 하는 방법

'''
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
print(a==b)
print(np.mean(a==b)) # True=1, False=0 의 평균
'''

'\na = np.array([1,2,3,4])\nb = np.array([1,2,3,5])\nprint(a==b)\nprint(np.mean(a==b)) # True=1, False=0 의 평균\n'

In [27]:
# y_test: 테스트 데이터의 답

y_predict = knn.predict(X_test)
print(np.mean(y_test==y_predict))

0.9736842105263158
